sudo: false
language: node_js
node_js:
    - 12
install:
    - npm ci
services:
    - redis
    - mongodb
cache:
    directories:
        - node_modules
script:
    - npm run build
    - npm test
